## nicht in Verwendung !!

version: '3'

services:
  mysqldb:
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /var/lib/mysql


# volumes dont work ...









