version: '3'

services:
  mysqldb:
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=bank
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=myDB
    volumes:
      - D:\DockerVolumes2:/var/lib/mysql










